### ISSUE TITLE
Bane of Wargs

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Dungeons-of-Kathallion.github.io#1]
@OcelotWalrus, could you create a page about Bane of Wargs? Don't forget to add it to the top bar or make a pull request first.

**Comment by OcelotWalrus** [comment]
Sure! What do you want me to write in it? Just the differences between the two engines?

**Comment by OcelotWalrus** [comment]
By the way, is it okay for you if make Bane Of Wargs use TOML instead of YAML?

**Comment by lumbar527** [comment]
Something like that, or your goals for it, or what it's about.

**Comment by OcelotWalrus** [comment]
Okay! It's the next thing I'll work on!

**Comment by lumbar527** [comment]
Thanks!

**Comment by OcelotWalrus** [comment]
By the way, I added a new cool thing to Bane Of Wargs: blacksmiths! You can sell weapons, or order weapons. You need gold and items to order weapons. More often it's metals that are required. They will be a new zone type soon: the forge. (Basically where you by/sell metals.)

**Comment by lumbar527** [comment]
Cool!

**Comment by OcelotWalrus** [comment]
I'm also thinking about adding something else: the church. It's where you will be exchanging your EXP with either special church knights weaponry or also HP!

**Comment by lumbar527** [comment]
If you want to discuss this then could you create an issue or discussion in Bane-Of-Wargs?
I'm fine with discussing stuff, it's just I don't think this is the place to do it.

**Comment by OcelotWalrus** [comment]
Sure. Because I think church need to do more than selling church weaponry and exchaning EXP with HP.
